### ISSUE TITLE
Innovative Features

### ISSUE THREAD

**Issue by challett** [challett/parking-meteor#3]
We need a couple at least

**Comment by nmjlelievre** [comment]
Sounds

**Comment by nmjlelievre** [comment]
Hourly weather forecast

**Comment by challett** [comment]
Anybody know the weather API we used for d04?

**Comment by challett** [comment]
Done weather

**Comment by challett** [comment]
Sounds are implemented

**Comment by nmjlelievre** [comment]
Phone message notification (?) [can show in popup on screen after certain amount of time]

**Comment by challett** [comment]
Weather: Done
Traffic: Done
Voucher Redemption is kinda innovative: Done
French Language Support: Needs a double check

No time for more ideas, closing ticket
