### ISSUE TITLE
Page Scaling

### ISSUE THREAD

**Issue by speence** [challett/parking-meteor#7]
Buttons and labels need to stay in their container when resizing the page

**Comment by challett** [comment]
Final EXE size should be fixed anyways.

**Comment by speence** [comment]
We need to decide on a size

**Comment by challett** [comment]
And find out how to set the size as fixed from an exe

**Comment by challett** [comment]
https://github.com/arboleya/electrify#customizing

**Comment by challett** [comment]
done
