### ISSUE TITLE
Ticket should disappear after hitting "done"

### ISSUE THREAD

**Issue by nmjlelievre** [challett/parking-meteor#9]
After pressing done once the ticket has been printed, it should not be visible upon return to <code>startPage</code>.

**Comment by challett** [comment]
I was thinking of a way to simulate scanning the ticket instead of typing in the _id.  Perhaps we could have a click event on the ticket that acts as a scan

**Comment by speence** [comment]
Perhaps the ticket should remain visible on the start page until the user removes it? This allows for more time for the user to top up the ticket

**Comment by challett** [comment]
Ticket data should not be updated once printed
